colang_version: 2.x
models:
  - type: main
    engine: openai
    model: llama-3.3-70b-versatile
    api_key_env_var: GROQ_API_KEY
    parameters:
      base_url: https://api.groq.com/openai/v1

instructions:
  - type: general
    content: |
      You are an Enterprise IT Assistant specialising in Kubernetes,
      Intel hardware, and enterprise networking.
      Only answer questions about these topics. Be professional and concise.

#rails:
  #input:
    #parallel: false
    #flows:
      #- check input for pii
      #- detect urgency
  #output:
    #parallel: false
    #flows:
      #- sanitize bot response
